### ISSUE TITLE
Nonable fields

### ISSUE THREAD

**Issue by smarie** [smarie/python-pyfields#44]
From #43 : 

As of now we seem to have to explicitly declare optionality for the "check type" to skip the type validation in case of a nullable field.

For example:

```python
from typing import Optional

class A:
     field1: Optional[int] = field(check_type=True, default=None)
     field2: Optional[int] = field(check_type=True)
```

Note that this is completely independent from  the fact that a field is optional or mandatory. However the usual python behaviour for typing is to consider nullable all arguments that have a `None` default value, see https://stackoverflow.com/a/57390124/7262247.

**Comment by smarie** [comment]
also we should make the value validators (another feature of pyfields) skip  validation in case `None` is passed.

**Comment by devashishshankar** [comment]
Thanks
