### ISSUE TITLE
Weird behavior when calling super().__init__

### ISSUE THREAD

**Issue by devashishshankar** [smarie/python-pyfields#53]
Let's say I want to call superclass init in my child class:

```
from pyfields import field, init_fields, get_field


class A:
    a = field(str, check_type=True)

    @init_fields()
    def __init__(self):
        pass


class B(A):
    b = field(str, check_type=True)

    @init_fields()
    def __init__(self):
        super(B, self).__init__(a=self.a)
        pass

print(B('a', 'b'))

```

This fails with the following Error:
```
    super(B, self).__init__(a=self.a)
TypeError: __init__() missing 1 required positional argument: 'b'
```

If I try the following:
```
from pyfields import field, init_fields, get_field


class A:
    a = field(str, check_type=True)

    @init_fields(a)
    def __init__(self):
        pass


class B(A):
    b = field(str, check_type=True)

    @init_fields()
    def __init__(self):
        super(B, self).__init__(a=self.a)
        pass

print("Init before calling B", B.__init__)
B(a='22', b='33')
print("Init after calling B", B.__init__)

```
This leads to the following:
```
Init before calling B <function B.__init__ at 0x108951cb0>
Init after calling B <function A.__init__ at 0x108951f80>
```
This is very dangerous, and was leading to a weird error in my code. Took me a while to figure out this was the cause.

I think the superclass constructor is being overriden by the child class. `setattr(objtype, '__init__', new_init)` in `init_makers.py`

Is calling superclass constructor not supported? 

I am using version 1.0.2

**Comment by smarie** [comment]
wow, very strange indeed ! This should definitely not happen. It is probably related to the fact that the `__init__` descriptor is not called in an intuitive way by `super` . I'll have a look, thanks a lot for reporting !

**Comment by smarie** [comment]
For some reason that seems to be a python bug, `super(B, self).__init__(a)` is not equivalent to `A.__init__(self, a=self.a)` when the `__init__` method is a method descriptor: `InitDescriptor.__get__(obj, objtype)` **is** called but when it is called through super, `objtype` is not replaced with `A`.

I'll have to find a workaround, that should not be too difficult. In the meantime, you can use `A.__init__(self, a=self.a)` as a constructor, it works.

**Comment by smarie** [comment]
I found a workaround but for python 3.6+ (where `__setname__` callback is called when the init descriptor is attached to the class). Unfortunately for earlier versions I still have no way to determine which class owns the init method to be created. I really thought that `objtype` in `InitDescriptor.__get__(obj, objtype)` was reliable...

**Comment by devashishshankar** [comment]
Thanks, using `A.__init__(self, a=self.a)` works for me.

**Comment by smarie** [comment]
I finally found a "clever" way to solve this in 1.0.3 :)
