### ISSUE TITLE
Incorrect work of lists in fields.

### ISSUE THREAD

**Issue by kolod** [smarie/python-pyfields#83]
I want to get a list of objects.
One of the fields in this object is a list.
When adding items to the field of one of the objects.
This element is added to the fields of all elements.
More precisely, all objects use one copy of the list. 

Example test:
``` python
#!/usr/bin/python3

import unittest
from pyfields import field, init_fields, make_init
from typing import List


class Test_make_init():

    test_list: List[str] = field(default=[])
    __init__ = make_init()


class Test_init_fields:

    test_list: List[str] = field(default=[])

    @init_fields
    def __init__(self) -> None:
        pass


class TestFields(unittest.TestCase):

    def test_make_init(self):

        # Prepera list
        TestObjects: List[Test_make_init] = []
        for i in range(3):
            TestObjects.append(Test_make_init())
            TestObjects[-1].test_list.append(f'{i}')

        # Check list
        for i in range(3):
            self.assertEqual(TestObjects[i].test_list, [f'{i}'])

    def test_init_fields(self):

        # Prepera list
        TestObjects: List[Test_init_fields] = []
        for i in range(3):
            TestObjects.append(Test_init_fields())
            TestObjects[-1].test_list.append(f'{i}')

        # Check list
        for i in range(3):
            self.assertEqual(TestObjects[i].test_list, [f'{i}'])


if __name__ == "__main__":
    unittest.main()
```

**Comment by smarie** [comment]
This is normal: `pyfields` follows strictly python's behaviour with `default`.
I think that in your case you probably wish to use `default_factory` as suggested in the [doc](https://smarie.github.io/python-pyfields/#b-default-value-factory):

> The behaviour with default values is the same than python's default: the same value is used for all objects. Therefore if your default value is a mutable object (e.g. a list) you should not use this mechanism, otherwise the same value will be shared by all instances that use the default

**Comment by smarie** [comment]
@kolod did the above answer work for you ? I'm closing the ticket now, please feel free to reopen if this is not the case.
